# Generated by Django 5.0.7 on 2024-07-16 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_location_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="descritpion",
            new_name="description",
        ),
    ]
